language: objective-c
matrix:
  include:
  - jdk: oraclejdk8
sudo: false
node_js:
  - "6.0"
install:
    - npm install
    - npm install -g cordova ios-deploy
script:
    - cordova prepare
after_script:
    - cordova build android
    - cordova build ios

