language: objective-c
sudo: false
node_js:
  - "6.0"
install:
    - brew install android-sdk
    - export ANDROID_HOME=/usr/local/opt/android-sdk
    - android -s update sdk --no-ui
    - npm install
    - npm install -g cordova ios-deploy
script:
    - cordova prepare
    - cordova build android
    - cordova build ios