language: objective-c
addons:
  artifacts:
    debug: true
sudo: false
node_js:
  - "6.0"
install:
    - brew install android-sdk
    - export ANDROID_HOME=/usr/local/opt/android-sdk
    - bash ./install-android-sdk
    - npm install
script:
    - ./node_modules/.bin/cordova prepare
    - ./node_modules/.bin/cordova build android
    - ./node_modules/.bin/cordova build ios
    - find . -name '.apk' -name '.app' -name '.ipa'
