language: objective-c
addons:
  artifacts:
    debug: true
sudo: false
node_js:
  - "6.0"
install:
    - brew install android-sdk
    - export ANDROID_HOME=/usr/local/opt/android-sdk
    - bash ./install-android-sdk
    - npm install
    - sudo npm install -g cordova ios-deploy
script:
    - cordova prepare
    - cordova build android
    - cordova build ios
    - find . -name '.apk' -name '.app' -name '.ipa'
