#!/bin/bash

expect -c '
set timeout -1   ;
spawn /usr/local/opt/android-sdk/tools/android -s update sdk --all -u -t tools,platform-tools,build-tools-23.0.3,android-23;
expect {
    "Do you accept the license" { exp_send "y\r" ; exp_continue }
    eof
}
'